import type { VocabWord } from '../src/types';

// AUTO-GENERATED by scripts/generateVocab.js — REVIEW the Vietnamese
// (machine translation) before merging into src/data/vocabularyData.ts.
// Generated: 2026-06-09T15:58:15.398Z

export const GENERATED_VOCAB: VocabWord[] = [
  // ── animals (generated) ──
  { id: 'g_ani_01', en: 'Wolf', vi: 'Sói', category: 'animals', difficulty: 2 },
  { id: 'g_ani_02', en: 'Donkey', vi: 'Con lừa', category: 'animals', difficulty: 3 },
  { id: 'g_ani_03', en: 'Shark', vi: 'Cá mập', category: 'animals', difficulty: 3 },
  { id: 'g_ani_04', en: 'Peacock', vi: 'Công', category: 'animals', difficulty: 3 },
  { id: 'g_ani_05', en: 'Panda', vi: 'Gấu Trúc', category: 'animals', difficulty: 4 },
  { id: 'g_ani_06', en: 'Zebra', vi: 'Ngựa vằn', category: 'animals', difficulty: 4 },
  { id: 'g_ani_07', en: 'Giraffe', vi: 'Hươu cao cổ', category: 'animals', difficulty: 4 },
  { id: 'g_ani_08', en: 'Hippo', vi: 'Hà mã', category: 'animals', difficulty: 4 },
  { id: 'g_ani_09', en: 'Squirrel', vi: 'Sóc', category: 'animals', difficulty: 3 },
  { id: 'g_ani_10', en: 'Bat', vi: 'Đánh bóng', category: 'animals', difficulty: 3 },
  { id: 'g_ani_11', en: 'Turkey', vi: 'Vụ đầu tư không như ý', category: 'animals', difficulty: 2 },

  // ── colors (generated) ──
  { id: 'g_col_01', en: 'Beige', vi: 'Becolor', category: 'colors', difficulty: 4 },
  { id: 'g_col_02', en: 'Violet', vi: 'Tím xanhcolor', category: 'colors', difficulty: 3 },
];
